### ISSUE TITLE
Vouchers for individuals / orgs outside of 'Individual Donors' pane?

### ISSUE THREAD

**Issue by geerlingguy** [amazeeio/DrupalCaresHalfMillionDollarHomepage#18]
It might be nice to either give a base '$100 credit' or some other voucher to each of the organizations and individuals listed outside the 'Individual Donors' pane.

It looks like the current code (https://github.com/amazeeio/PixelsForDrupal/blob/8054b777daf9b936c86937fec7a4dde05e7c6088/admin/voucher-admin.php#L109) points at the "Individual Donors" list.

There is also a list of "Thank you to these individual #DrupalCares supporters" who are called out as having given _at least $1000_ individually, just above the Individual Donors list, and above that there are a few groupings of organizations who supported it.

Even if the vouchers for orgs are only $10 or $50 or $100... it might be nice to give them a little way to officially memorialize their support on the Pixels for Drupal site.

**Comment by seanhamlin** [comment]
Hey @geerlingguy, the change here would be a simple one, the above DOM selector actually finds the d.o membership donations too.

https://github.com/amazeeio/PixelsForDrupal/blob/8054b777daf9b936c86937fec7a4dde05e7c6088/admin/voucher-admin.php#L123-L125

It is just that they show up with the value of $0. So we could easily just set a default amount instead. $50 is enough for a 3x3 and a 1x1 on the grid so that might be a good start? We can always bump manually up anyone that has donated more. We likely just need code to ensure we don't 'downgrade' the amounts for anyone on subsequent imports.

**Comment by geerlingguy** [comment]
That seems like it would be fair; and IMO it would be nice in one sense to cap things at some level so we don't just have like 50% of the pixels taken up by the top 3 or 4 donating orgs.

Or maybe not, to encourage some orgs to go waaaaay above and beyond 🤪
